# Generated by Django 2.1 on 2018-11-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=6)),
                ('stock', models.PositiveIntegerField()),
                ('img', models.CharField(max_length=120)),
                ('rating', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('M', 'Music'), ('B', 'Books'), ('S', 'Sports'), ('A', 'Art')], max_length=1)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
