# Generated by Django 2.1 on 2018-11-21 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('governorate', models.CharField(choices=[('A', 'Al Asimah Governorate'), ('H', 'Hawalli Governorate'), ('F', 'Farwaniya Governorate'), ('M', 'Mubarak Al-Kabeer Governorate'), ('AH', 'Ahmadi Governorate'), ('J', 'Jahra Governorate')], max_length=2)),
                ('area', models.CharField(max_length=40)),
                ('block', models.PositiveIntegerField()),
                ('street', models.CharField(max_length=120)),
                ('house_building', models.CharField(max_length=40)),
                ('floor', models.PositiveIntegerField()),
                ('appartment', models.CharField(max_length=10)),
                ('extra_directions', models.TextField()),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=6)),
                ('stock', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('rating', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('M', 'Music'), ('B', 'Books'), ('S', 'Sports'), ('A', 'Art'), ('T', 'Tech')], max_length=1)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('0', 'Ordered'), ('P', 'Packed'), ('D', 'Delivered')], max_length=2)),
                ('address', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Address')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('item', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Item')),
                ('order', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='api.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNo', models.CharField(max_length=9, null=True)),
                ('bio', models.TextField(max_length=500)),
                ('img', models.ImageField(null=True, upload_to='')),
                ('birth_date', models.DateField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orprofile', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='addprofile', to='api.Profile'),
        ),
    ]
