# Generated by Django 2.1 on 2018-11-20 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='img',
            new_name='image',
        ),
    ]
