# Generated by Django 2.1 on 2018-11-20 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20181120_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('governorate', models.CharField(choices=[('A', 'Al Asimah Governorate'), ('H', 'Hawalli Governorate'), ('F', 'Farwaniya Governorate'), ('M', 'Mubarak Al-Kabeer Governorate'), ('AH', 'Ahmadi Governorate'), ('J', 'Jahra Governorate')], max_length=1)),
                ('block', models.PositiveIntegerField()),
                ('street', models.CharField(max_length=120)),
                ('house_building', models.CharField(max_length=120)),
                ('floor', models.CharField(max_length=120)),
                ('extra_directions', models.TextField()),
                ('default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('M', 'Music'), ('B', 'Books'), ('S', 'Sports'), ('A', 'Art'), ('T', 'Tech')], max_length=1),
        ),
    ]
