# Generated by Django 2.1 on 2018-11-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181120_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='area',
            field=models.CharField(default='Jabriya', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='floor',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='address',
            name='house_building',
            field=models.CharField(max_length=40),
        ),
    ]
