# Generated by Django 2.1 on 2018-11-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181125_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('O', 'Ordered'), ('P', 'Packed'), ('D', 'Delivered'), ('C', 'Cart')], default=3, max_length=2),
        ),
    ]
