# Generated by Django 2.1 on 2018-11-21 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_auto_20181120_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNo', models.CharField(max_length=9)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='governorate',
            field=models.CharField(choices=[('A', 'Al Asimah Governorate'), ('H', 'Hawalli Governorate'), ('F', 'Farwaniya Governorate'), ('M', 'Mubarak Al-Kabeer Governorate'), ('AH', 'Ahmadi Governorate'), ('J', 'Jahra Governorate')], max_length=2),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Profile'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
