# Generated by Django 2.1 on 2018-11-25 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181125_0530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='profile',
        ),
    ]
