# Generated by Django 2.1 on 2018-11-25 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181125_0627'),
        ('api', '0004_auto_20181124_1005'),
    ]

    operations = [
    ]
